[project]
name = "integrprog"
version = "0.1.0"
description = "Integrated Programming Course Labs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyQt6>=6.4.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
